name: calculator_app
description: A Flutter project for a simple calculator

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.0.0 # Ensure this is added if you're using the math_expressions package.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Add this line to include flutter_lints for linting.

flutter:
  uses-material-design: true
